ProjectManagement/ProjectManagement/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using ProjectManagement.Models;
using ProjectManagement.Repository;

namespace ProjectManagement.Controllers
{
    [Route("[controller]")]
    public class ProjectController : Controller
    {
        #region Global Declaration
        // Global Declaration of variables
        readonly IProjectRepository _projectRepository;
        #endregion

        #region ProjectController Constructor
        // Constructor of ProjectController
        public ProjectController(IProjectRepository projectRepository) => _projectRepository = projectRepository;
        #endregion

        #region Action to List Projects
        // Action to list projects
        [Route("[action]")]
        public IActionResult Index(int page = 1, int pageSize = 5, string search = null)
        {
            if (!string.IsNullOrEmpty(search))
            {
                PagedList<Project> foundProjects = new PagedList<Project>(_projectRepository.SearchProject(search), page, pageSize);
                return View("Index", foundProjects);
            }
            PagedList<Project> projects = new PagedList<Project>(_projectRepository.GetAllProjects(), page, pageSize);
            return View("Index", projects);
        }
        #endregion

        #region Action to view details of Project
        // Action to view details of project
        [Route("[action]")]
        public IActionResult Details(int id)
        {
            var project = _projectRepository.GetProjectDetails(id);
            if (project == null)
                return View("ProjectNotFound");
            return View(project);
        }
        #endregion

        #region Action to save Project
        // Action to add and edit project
        [Route("[action]")]
        public IActionResult Save(int id)
        {
            ViewBag.ProjectManagerId = _projectRepository.GetManagerList();
            var project = _projectRepository.GetProjectDetails(id);
            if (id == 0)
                project = new Project();
            else if (project == null)
                return View("ProjectNotFound");
            return View(project);
        }

        [HttpPost]
        [Route("[action]")]
        public IActionResult Save(Project project)
        {
            ViewBag.ProjectManagerId = _projectRepository.GetManagerList();
            if (project.Id == 0)
            {
                if (_projectRepository.GetProjectName(project.Name) != null)
                {
                    ModelState.AddModelError("Name", "Project already exists.");
                    return View(project);
                }
            }

            if (ModelState.IsValid)
            {
                _projectRepository.SaveProject(project);
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Action to delete Project
        // Action to delete project
        [Route("[action]")]
        public IActionResult Delete(int id)
        {
            var project = _projectRepository.GetProjectDetails(id);
            if (project == null)
                return View("ProjectNotFound");
            return View(project);
        }

        [HttpPost, ActionName("Delete")]
        [Route("[action]")]
        public IActionResult DeleteConfirmed(int id)
        {
            _projectRepository.DeleteProject(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

ProjectManagement/ProjectManagement/Controllers/ProjectManagerController.cs
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using ProjectManagement.Models;
using ProjectManagement.Repository;

namespace ProjectManagement.Controllers
{
    [Route("[controller]")]
    public class ProjectManagerController : Controller
    {
        #region Global Declaration
        // Global Declaration of variables
        readonly IProjectManagerRepository _projectManagerRepository;
        #endregion

        #region ProjectManagerController Constructor
        // Constructor of ProjectController
        public ProjectManagerController(IProjectManagerRepository projectManagerRepository) =>
            _projectManagerRepository = projectManagerRepository;
        #endregion

        #region Action to List Project Managers
        // Action to list project managers
        [Route("[action]")]
        public IActionResult Index(int page = 1, int pageSize = 5, string search = null)
        {
            if (!string.IsNullOrEmpty(search))
            {
                PagedList<ProjectManager> foundProjectManagers = new PagedList<ProjectManager>(_projectManagerRepository.SearchProjectManager(search), page, pageSize);
                return View("Index", foundProjectManagers);
            }
            PagedList<ProjectManager> projectManagers = new PagedList<ProjectManager>(_projectManagerRepository.GetAllProjectManagers(), page, pageSize);
            return View("Index", projectManagers);
        }
        #endregion

        #region Action to view details of Project Manager
        // Action to view details of project manager
        [Route("[action]")]
        public IActionResult Details(int id)
        {
            var projectManager = _projectManagerRepository.GetProjectManagerDetails(id);
            if (projectManager == null)
                return View("ProjectManagerNotFound");
            return View(projectManager);
        }
        #endregion

        #region Action to save Project Manager
        // Action to add and edit project manager
        [Route("[action]")]
        public IActionResult Save(int id)
        {
            var projectManager = _projectManagerRepository.GetProjectManagerDetails(id);
            if (id == 0)
                projectManager = new ProjectManager();
            else if (projectManager == null)
                return View("ProjectManagerNotFound");
            return View(projectManager);
        }

        [HttpPost]
        [Route("[action]")]
        public IActionResult Save(ProjectManager projectManager)
        {
            if (projectManager.Id == 0)
            {
                if (_projectManagerRepository.GetEmail(projectManager.Email) != null)
                {
                    ModelState.AddModelError("Email", "Email already exists.");
                    return View(projectManager);
                }
                else if (_projectManagerRepository.GetContact(projectManager.Contact) != null)
                {
                    ModelState.AddModelError("Contact", "Contact already exists.");
                    return View(projectManager);
                }
            }
            if (ModelState.IsValid)
            {
                _projectManagerRepository.SaveProjectManager(projectManager);
                return RedirectToAction("Index");
            }
            ModelState.Clear();
            return View();
        }
        #endregion

        #region Action to delete Project Manager
        // Action to delete project manager
        [Route("[action]")]
        public IActionResult Delete(int id)
        {
            var projectManager = _projectManagerRepository.GetProjectManagerDetails(id);
            if (projectManager == null)
                return View("ProjectManagerNotFound");
            return View(projectManager);
        }

        [HttpPost, ActionName("Delete")]
        [Route("[action]")]
        public IActionResult DeleteConfirmed(int id)
        {
            _projectManagerRepository.DeleteProjectManager(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

ProjectManagement/ProjectManagement/Views/Shared/ProjectManagerNotFound.cshtml
@{
    ViewData["Title"] = "ProjectManagerNotFound";
}

<div class="card text-center p-5">
    <h1 class="mb-3">The Project Manager you requested cannot be found. </h1>
    <h2 class="mb-3">You can add a new Project Manager.</h2>
    <a asp-action="Index" asp-controller="Project" class="btn btn-primary w-25 mx-auto">Back to Project Manager List</a>
</div>

ProjectManagement/ProjectManagement/Views/Shared/ProjectNotFound.cshtml
@{
    ViewData["Title"] = "ProjectNotFound";
}

<div class="card text-center p-5">
    <h1 class="mb-3">The Project you requested cannot be found. </h1>
    <h2 class="mb-3">You can add a new Project.</h2>
    <a asp-action="Index" asp-controller="Project" class="btn btn-primary w-25 mx-auto">Back to Project List</a>
</div>

ProjectManagement/ProjectManagement/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/Logo.png">
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link href="~/css/Style.css" rel="stylesheet" />
    <link href="~/css/toastr.min.css" rel="stylesheet" />
    <link href="~/css/PagedList.css" rel="stylesheet" />
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/Script.js"></script>
    <title>Project Management</title>
</head>
<body>
    <div class="navbar navbar-expand-lg bg-light navbar-light">
        <img src="~/images/Logo.png" asp-append-version="true" width="50" height="50" />
        <a asp-action="Index" asp-controller="Home" class="navbar-brand font-weight-bold text-dark ml-2">Project Management</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-action="Index" asp-controller="Project">Project</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-action="Index" asp-controller="ProjectManager">Project Manager</a>
            </li>
        </ul>
    </div>

    <div class="container py-5 mb-3 mx-auto">
        @RenderBody()
    </div>

    <div class="bg-light text-center p-3 fixed-bottom">&copy; All Rights Reserved.</div>
</body>
</html>